### ISSUE TITLE
gddgrowTT -> gddgrow5

### ISSUE THREAD

**Issue by aulemahal** [clix-meta/clix-meta#21]
# Please explain briefly what is wrong

The var name suggests a user input "TT", but the threshold is set in the `PARAMETER_definition` column, at 5 °C.

# Suggest specific changes to the `index_definition` table

 
| *Column name* | *Present (wrong) entry* | *Suggested correction* |
| ------ | ------ | ------ |
| VarName | gddgrow{TT} | gddgrow5 |
| Input |  |  |
| OUTPUT_standard_name|  |  |
| OUTPUT_cell_methods |  |  |
| OUTPUT_units |  |  |
| OUTPUT_proposed_standard_name |  |  |
| OUTPUT_proposed_cell_methods |  |  |
| OUTPUT_proposed_units |  |  |
| OUTPUT_long_name |  |  |
| OUTPUT_reference |  |  |
| allowed_freq |  |  |
| default_freq |  |  |
| index_function |  |  |
| N_parameters |  |  |
| parameter_name |  |  |
| PARAMETER_definition |  |  |
| ET_short_name |  |  |
| ET_long_name |  |  |
| ET_definition |  |  |
| ET_comment |  |  |

**Comment by larsbarring** [comment]
Thank you @aulemahal for spotting this. 

In fact, this index was defined by ET-SCI to have a"user-defined location-specific base temperature", cf. [CLIMPACT2 Appendix A](https://climpact-sci.org/assets/climpact2-user-guide.pdf). So, the corrections should be the other way around, i.e. to make the parameter user-defined as **`{TT}`**. This is now corrected in the master branch.

Is there specific need to define `gddgrow5 ` this can easily be done. But the aim with all the **`{...}`** indices is to allow for flexibility in parameter values without the need to have a separate entry for each and every one. Quite a few specific ones are in the table, but this is because they were defined before this work started.

**Comment by aulemahal** [comment]
Thanks! That solves it.
