### ISSUE TITLE
Missing indices in yaml file

### ISSUE THREAD

**Issue by bzah** [clix-meta/clix-meta#58]
# Describe your question, request or issue here:
I'm using the 0.3.0 release archive.
There are 52 indices in the master table which are missing from the yaml.

<details>
  <summary>Missing indices: (click me!)</summary>
  
- wsdi
- wsdi{ND}
- csdi
- csdi{ND}
- tx95t
- tx{D}tn{D}
- tx{D}tn{D}gt{PRC}p
- txb{D}tnb{D}
- tx{D}tn[D}lt{PRC}p
- gsl
- gsstart
- gsend
- gsgdd
- HI
- BEDD
- HWN(EHF/Tx90/Tn90)
- HWF(EHF/Tx90/Tn90)
- HWD(EHF/Tx90/Tn90)
- HWM(EHF/Tx90/Tn90)
- HWA(EHF/Tx90/Tn90)
- CWN_ECF
- CWF_ECF
- CWD_ECF
- CWM_ECF
- CWA_ECF
- UTCI
- TCI
- TCI60
- TCI80
- r95ptot
- r99ptot
- r{PRC}ptot
- r95p
- r99p
- r75ptot
- r95p
- SPI
- SPEI
- SPI6
- SPI3
- PET
- SSp
- CC
- CC2
- CC6
- CD
- CW
- WD
- WW
- faf
- lsf
- txmax5daymean
</details>

Beside, the index **r75p** is missing from both the xls and the yaml.
I think it's a copy-paste mistake because **r95p** is present twice in rows 126 and 133.

**Comment by zklaus** [comment]
Thanks for bringing this up, @bzah. From a sample of the indices, it seems these are the ones that are marked as not ready, i.e. the `ready` column contains a `0`. Those are left out on purpose because the available metadata information is not yet sufficient.
For some, this may be a wrong or outdated assessment, so if you think we could mark some of them as ready or know how to complete the metadata, that would be great!

Until then, they are in there basically as drafts, to be completed.

**Comment by bzah** [comment]
Thanks @zklaus I understand.
What is the minimal requirement for an index to become ready ?

Also, the README states:
> These include yaml files that are up-to-date with the corresponding tables of the spreadsheet file.

IMHO, it would be great to clarify this sentence with indices' readiness.

**Comment by larsbarring** [comment]
Good suggestion. I will look into this and also fix the `r75p` mistake.
