### ISSUE TITLE
Variable aliases: "adjust" suffix should be "Adjust" (uppercase)

### ISSUE THREAD

**Issue by bzah** [clix-meta/clix-meta#63]
According to [cordex.org](https://cordex.org/data-access/bias-adjusted-rcm-data/):
> Under the CORDEX-Adjust project the search facet “Bias Adjustment” replaces the “Downscaling Realisation” facet which is available under the CORDEX project. The same information concerning downscaling realisation is available as the first element of the “Bias Adjustment” facet. In order to avoid any confusion and to clearly distinguish original and bias-adjusted CORDEX simulation data, the CORDEX variable names are modified by appending ‘Adjust’ to the variable names, for example: Precipitation (pr to prAdjust), Near-Surface Air Temperature (tas to tasAdjust) etc.

Unless there are datasets using a full lowercase convention, I think the following `aliases` of the `variables` sheet:
"pradjust", "tasadjust", "tasmaxadjust", "tasminadjust", "hursadjust" ; should be renamed into 
"prAdjust", "tasAdjust", "tasmaxAdjust", "tasminAdjust", "hursAdjust".

**Comment by larsbarring** [comment]
The CF Conventions do not standardize names, but recommends (Section 2.3) that names should not be distinguished purely by case. But I agree with you and have thus added the `*Adjust` alternatives to the list of variable aliases, rather than replacing the `*adjust` ones. Thanks for raising this issue!

A PR is on its way, but will take a couple of weeks.

**Comment by pagecp** [comment]
I think that we should also enforce the case, because tools like NCO and others distinguish with case, e.g. pradjust is not the same as prAdjust:

```
% ncatted -O -a units,pradjust,o,c,'kg m-2 s-1' aa.nc
ncatted: ERROR File contains no variables or groups that match name "pradjust" so attribute "units" cannot be changed
% ncatted -O -a units,prAdjust,o,c,'kg m-2 s-1' aa.nc
```

This is beyond CF, like the Data Request of CMIP6 is also beyond CF. I think that we still follow the CF recommendation that names should not be distinguished purely by case, as we won't have pradjust AND prAdjust with different meanings. We just enforce that we must have prAdjust. This ensures better support of the existing numerous tools, because if one user uses prADJUST and one of the processing tools in a workflow chain gives errors because it rather expects prAdjust, that would be bad for users and automation.

**Comment by larsbarring** [comment]
I think that this is something different from the intended use of the CLIX-META variable table. This table is [only] intended to provide a link between the names used in the master table (which so far follows the CMIP data request) and some commonly used alternative variable names.

In principle, I think that the list of aliases could be all lowercase, in which case the software have to create a lowercase variant of the variable name to use with CLIX-META tables. Still the software should [of course!] keep the original variable name and use it when producing results. But we did not go that way, instead we allow several lower-/uppercase variants in an attempt to be user-friendly. In this spirit we also include several commonly used names that are not in the CMIP data request. I am not convinced that CLIX-META is the place/tool to enforce some naming convention. What do you think?

**Comment by pagecp** [comment]
I understand better now: for the intended use of the CLIX-META variable table and to provide the link between the names of the master table and alternative variable names, we can have variants then, as we will never have anyway a variable prAdjust and pradjust for example with a different meaning. 
But it should be clear to the users that the CLIX-META variable table is not the standard names that should be used. Having all lowercase would in fact mean for the software to be case-insensitive in order to use the CLIX-META variable table. I like this approach as long as it is clear for users in the documentation of the table.

**Comment by larsbarring** [comment]
Thanks @pagecp! Following your comment I have updated the README.md in the PR.
